# Generated by Django 5.2.9 on 2026-08-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultorio', models.CharField(default='Dental Clinic', max_length=150, verbose_name='Nombre del consultorio')),
                ('nombre_dentista', models.CharField(default='Dr. Nombre Apellido', max_length=200, verbose_name='Nombre del dentista')),
                ('telefono', models.CharField(default='+52 55 1234 5678', max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(default='Calle, Número, Colonia, Ciudad', max_length=300, verbose_name='Dirección')),
                ('zona_horaria', models.CharField(choices=[('America/Mexico_City', 'Ciudad de México (CST/CDT, UTC-6/UTC-5)'), ('America/Monterrey', 'Monterrey (CST/CDT, UTC-6/UTC-5)'), ('America/Tijuana', 'Tijuana (PST/PDT, UTC-8/UTC-7)'), ('America/Cancun', 'Cancún (EST, UTC-5)'), ('America/Chihuahua', 'Chihuahua (MST/MDT, UTC-7/UTC-6)')], default='America/Mexico_City', max_length=50, verbose_name='Zona horaria')),
            ],
            options={
                'verbose_name': 'Configuración del consultorio',
                'verbose_name_plural': 'Configuración del consultorio',
            },
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, verbose_name='Día')),
                ('activo', models.BooleanField(default=True, verbose_name='Día laboral')),
                ('hora_apertura', models.TimeField(default='09:00', verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(default='18:00', verbose_name='Hora de cierre')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='configuracion.configuracionconsultorio')),
            ],
            options={
                'verbose_name': 'Horario del día',
                'verbose_name_plural': 'Horarios por día',
                'ordering': ('dia',),
                'unique_together': {('consultorio', 'dia')},
            },
        ),
    ]
