# Generated by Django 5.2.9 on 2026-08-26 01:21

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=core.encrypted_fields.EncryptedCharField(verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=core.encrypted_fields.EncryptedCharField(verbose_name='Teléfono'),
        ),
    ]
