# Generated by Django 5.2.9 on 2026-08-26 01:21

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueohorario',
            name='motivo',
            field=core.encrypted_fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=core.encrypted_fields.EncryptedTextField(max_length=500),
        ),
    ]
